[package]
name = "spl_rust"
version = "0.1.0"
edition = "2018"

[dependencies]
aes-gcm = "0.10"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crc32fast = "1.3"
hex = "0.4"
